name: Tests code and builds docker image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  test_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'Code/backend'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install nodejs dependencies
        run: npm ci
      - name: Test code
        run: npm run test src/

  test_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'Code/frontend'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install nodejs dependencies
        run: npm ci
      - name: Test code
        run: npm run test
          
  dockerimage_frontend:
    needs: [test_backend, test_frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: Code/frontend/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-aseguramiento:latest
        
  dockerimage_backend:
    needs: [test_backend, test_frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: Code/backend/  # Corrected this line
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-aseguramiento:latest
